spring:
  application:
    name: hr-payroll
  datasource:
    url: jdbc:h2:mem:testdb
    data-username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8002
