spring:
  application:
    name: hr-worker
  datasource:
    url: jdbc:h2:mem:testdb
    data-username: sa
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000
