spring:
  application:
    name: hr-worker
  datasource:
    url: jdbc:h2:mem:testdb
    data-username: sa
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8001
